/* 4 bài tin tức mẫu. Ảnh trên - tiêu đề dưới - mô tả - ngày đăng có icon lịch. */

module.exports = [
  {
    slug: "lich-tong-ve-sinh-nha-cua-don-tet",
    title: "Lịch tổng vệ sinh nhà cửa đón Tết: nên bắt đầu từ khi nào?",
    seoTitle: "Lịch tổng vệ sinh nhà đón Tết",
    date: "2026-08-24",
    dateText: "24/08/2026",
    img: "hero-1",
    excerpt:
      "Đợi tới 27–28 Tết mới gọi dịch vụ là lúc giá cao nhất và khó đặt được lịch nhất. Đây là cách chia nhỏ công việc trong bốn tuần để nhà sạch mà không kiệt sức.",
    body: [
      { p: "Năm nào cũng vậy: khoảng 25 tháng Chạp trở đi, mọi đơn vị vệ sinh tại Nha Trang đều kín lịch và giá tăng 30–50%. Không phải vì các công ty muốn tăng giá, mà vì nhân sự có hạn trong khi tất cả các gia đình cùng dồn vào một tuần." },
      { p: "Cách giải quyết đơn giản: đừng dồn tất cả vào một buổi. Dưới đây là lịch bốn tuần chúng tôi vẫn tư vấn cho khách hàng quen." },
      { h2: "Tuần 1 — Xử lý những thứ cần thời gian khô" },
      { p: "Bắt đầu từ rèm cửa, thảm, nệm và sofa. Đây là nhóm cần giặt và phơi lâu, làm sớm để không vướng vào những ngày cận Tết bận rộn. Nếu thuê dịch vụ giặt nệm sofa, thời điểm này giá vẫn ở mức bình thường và dễ chọn khung giờ." },
      { p: "Cũng nên tranh thủ tuần này để thanh lý đồ không dùng. Việc này tốn thời gian ra quyết định hơn là công sức, làm sớm sẽ giúp các tuần sau nhẹ đi nhiều." },
      { h2: "Tuần 2 — Bếp và nhà vệ sinh" },
      { p: "Hai khu vực bẩn nhất và mất công nhất. Tẩy dầu mỡ máy hút mùi, vệ sinh lò nướng, làm sạch ron gạch, tẩy cặn vôi thiết bị vệ sinh. Làm xong hai khu này coi như đã qua được nửa khối lượng công việc." },
      { h2: "Tuần 3 — Cửa kính, trần và những chỗ trên cao" },
      { p: "Quạt trần, đèn chùm, nóc tủ, khe cửa lùa — những nơi cả năm không ai đụng tới. Cần thang và nên có người hỗ trợ. Nếu nhà có kính lớn hoặc ban công cao, đây là hạng mục nên thuê dịch vụ vì rủi ro té ngã là có thật." },
      { h2: "Tuần 4 — Hoàn thiện và trang trí" },
      { p: "Tuần cuối chỉ còn lau sàn tổng thể, sắp xếp lại đồ đạc và bày biện. Nhẹ nhàng và vui vẻ, đúng tinh thần đón Tết." },
      { h2: "Nếu muốn thuê trọn gói" },
      { p: "Với gia đình bận rộn, gói tổng vệ sinh trọn gói vẫn là lựa chọn hợp lý nhất. Lời khuyên duy nhất: đặt lịch trước ít nhất ba tuần. Khách đặt sớm được chọn khung giờ đẹp và giữ nguyên giá thường ngày." },
    ],
  },
  {
    slug: "chon-dich-vu-ve-sinh-uy-tin",
    title: "Năm dấu hiệu nhận biết một đơn vị vệ sinh làm ăn tử tế",
    seoTitle: "Cách chọn đơn vị vệ sinh uy tín",
    date: "2026-08-12",
    dateText: "12/08/2026",
    img: "hero-2",
    excerpt:
      "Giá rẻ bất thường, không khảo sát mà vẫn báo giá chắc nịch, nhân viên không đồng phục — những tín hiệu nên cân nhắc trước khi giao nhà cho ai đó.",
    body: [
      { p: "Thị trường dịch vụ vệ sinh gần như không có rào cản gia nhập: một chiếc xe máy, vài chai hoá chất và một số điện thoại là đủ để nhận việc. Điều đó khiến chất lượng chênh lệch rất lớn, còn người thiệt là khách hàng." },
      { p: "Dưới đây là năm tiêu chí thực tế giúp bạn sàng lọc, áp dụng được cho cả dịch vụ vệ sinh lẫn giúp việc gia đình." },
      { h2: "1. Có khảo sát trước khi báo giá" },
      { p: "Một đơn vị nghiêm túc sẽ hỏi diện tích, số phòng, tình trạng hiện tại, hoặc tới xem trực tiếp với công trình lớn. Nơi nào chốt giá ngay qua điện thoại mà không hỏi gì thường sẽ phát sinh khi tới nơi, hoặc làm qua loa cho vừa với số tiền đã báo." },
      { h2: "2. Giá không rẻ tới mức vô lý" },
      { p: "Chi phí nhân công, hoá chất và khấu hao máy móc là những con số có thật. Một mức giá thấp hơn mặt bằng 40–50% chỉ có thể đến từ việc cắt giờ làm, dùng hoá chất trôi nổi, hoặc trả lương nhân viên quá thấp — và bạn sẽ nhận lại đúng chất lượng tương ứng." },
      { h2: "3. Nhân viên có đồng phục và hồ sơ rõ ràng" },
      { p: "Bạn đang cho một người lạ vào nhà mình. Hãy hỏi thẳng: nhân viên có hồ sơ lý lịch không, công ty có chịu trách nhiệm nếu xảy ra mất mát không. Đơn vị làm ăn tử tế sẽ trả lời được ngay và có giấy tờ chứng minh." },
      { h2: "4. Nói rõ hoá chất sử dụng" },
      { p: "Đặc biệt quan trọng với nhà có trẻ nhỏ, người già hoặc thú cưng. Hãy hỏi tên sản phẩm và yêu cầu xem chai. Nếu nhân viên sang chiết vào chai không nhãn và không nói được đó là gì, đó là dấu hiệu đáng lo." },
      { h2: "5. Có cam kết làm lại nếu chưa đạt" },
      { p: "Đây là phép thử đơn giản nhất về mức độ tự tin. Đơn vị tin vào chất lượng của mình sẽ sẵn sàng cam kết làm lại miễn phí nếu khách chưa hài lòng trong buổi nghiệm thu. Nơi né tránh câu hỏi này thường có lý do." },
      { h2: "Tóm lại" },
      { p: "Đừng chọn chỉ dựa vào giá. Một buổi vệ sinh làm ẩu khiến bạn phải làm lại, hoặc tệ hơn là làm hỏng sàn gỗ, xước kính, sẽ đắt hơn nhiều so với khoản chênh lệch ban đầu." },
    ],
  },
  {
    slug: "ve-sinh-nha-mua-mua-nha-trang",
    title: "Chống ẩm mốc mùa mưa cho nhà ở Nha Trang",
    date: "2026-07-28",
    dateText: "28/07/2026",
    img: "hero-3",
    excerpt:
      "Độ ẩm cao và hơi muối biển khiến nhà ở Nha Trang xuống cấp nhanh hơn nơi khác. Vài biện pháp đơn giản giúp hạn chế nấm mốc và mùi hôi trong mùa mưa.",
    body: [
      { p: "Nhà ở vùng biển có một đặc thù mà nhiều người mới chuyển tới không lường trước: hơi muối trong không khí kết hợp độ ẩm cao làm kim loại gỉ nhanh, tường bong tróc và nấm mốc phát triển mạnh, nhất là vào mùa mưa từ tháng 9 tới tháng 12." },
      { h2: "Nhận biết sớm các điểm dễ mốc" },
      { p: "Nấm mốc luôn xuất hiện trước ở những nơi ít không khí lưu thông: mặt sau tủ quần áo kê sát tường, góc trần phòng tắm, gầm cầu thang, khu vực sau tủ lạnh và trong tủ bếp dưới bồn rửa." },
      { p: "Dấu hiệu đầu tiên thường là mùi ẩm chứ không phải vết đen. Nếu mở tủ quần áo thấy mùi lạ, hãy kiểm tra mặt sau tủ ngay thay vì chỉ xịt thơm." },
      { h2: "Bốn việc nên làm định kỳ" },
      { p: "<strong>Kéo tủ ra khỏi tường ít nhất 5cm.</strong> Khoảng hở này cho phép không khí lưu thông và tạo khác biệt rõ rệt. Đây là biện pháp đơn giản nhất mà hiệu quả nhất." },
      { p: "<strong>Mở cửa thông gió vào buổi trưa nắng.</strong> Ngược với suy nghĩ thông thường, đóng kín cửa suốt mùa mưa khiến hơi ẩm bị giữ lại bên trong. Hãy tận dụng những giờ hửng nắng để thay không khí." },
      { p: "<strong>Lau khô ngay các bề mặt kim loại.</strong> Bản lề, tay nắm cửa, khung cửa nhôm nên được lau khô và tra dầu định kỳ để hạn chế gỉ do hơi muối." },
      { p: "<strong>Kiểm tra và thông cống thoát nước ban công.</strong> Nước đọng là nguồn ẩm lớn nhất, và cũng là nguyên nhân thấm ngược vào tường." },
      { h2: "Khi nấm mốc đã xuất hiện" },
      { p: "Không nên chỉ lau bằng nước javel rồi sơn đè lên. Cách này diệt phần nhìn thấy nhưng bào tử vẫn còn trong lớp vữa, vài tháng sau sẽ mọc lại. Cần xử lý bằng dung dịch diệt nấm chuyên dụng, để khô hoàn toàn rồi mới xử lý bề mặt." },
      { p: "Với diện tích mốc lớn hoặc mốc ở trần cao, nên gọi dịch vụ vì công việc này cần đồ bảo hộ — hít phải bào tử nấm mốc trong không gian kín có thể gây kích ứng hô hấp." },
    ],
  },
  {
    slug: "bao-duong-nem-sofa-dinh-ky",
    title: "Bao lâu nên giặt nệm và sofa một lần?",
    date: "2026-07-05",
    dateText: "05/07/2026",
    img: "hero",
    excerpt:
      "Nệm là món đồ tiếp xúc với cơ thể tám tiếng mỗi đêm nhưng hiếm khi được làm sạch. Tần suất hợp lý và những dấu hiệu cho thấy đã tới lúc.",
    body: [
      { p: "Chúng ta giặt ga giường hằng tuần nhưng gần như không bao giờ nghĩ tới việc làm sạch chính chiếc nệm bên dưới. Trong khi đó, mỗi đêm cơ thể thải ra mồ hôi và tế bào da chết, phần lớn thấm qua ga xuống lớp mút." },
      { h2: "Tần suất khuyến nghị" },
      { p: "<strong>Nệm:</strong> 6 tháng một lần với gia đình bình thường. Rút ngắn còn 3–4 tháng nếu nhà có trẻ nhỏ, người bị viêm mũi dị ứng, hoặc thú cưng ngủ chung." },
      { p: "<strong>Sofa vải:</strong> 6–12 tháng. Sofa phòng khách dùng nhiều, có trẻ ăn uống trên đó thì nên 6 tháng." },
      { p: "<strong>Thảm:</strong> 3–6 tháng. Thảm ở lối đi chính bám bụi nhanh hơn nhiều so với thảm trang trí." },
      { p: "<strong>Rèm cửa:</strong> 12 tháng, hoặc 6 tháng nếu nhà gần đường lớn nhiều bụi." },
      { h2: "Những dấu hiệu không nên bỏ qua" },
      { p: "Nếu bạn thức dậy với triệu chứng hắt hơi, nghẹt mũi hoặc ngứa mắt nhưng ra khỏi nhà lại hết, khả năng cao nguyên nhân nằm ở nệm. Mạt bụi là tác nhân gây dị ứng phổ biến nhất trong nhà và chúng sống chủ yếu trong nệm, gối và thảm." },
      { p: "Các dấu hiệu khác: nệm có mùi ẩm dù đã phơi, xuất hiện vết ố vàng, hoặc bề mặt sờ vào thấy nhám và bám dính." },
      { h2: "Giữa các lần giặt nên làm gì?" },
      { p: "Hút bụi bề mặt nệm mỗi tháng một lần bằng đầu hút chuyên dụng. Xoay và lật nệm mỗi ba tháng để mòn đều. Dùng tấm bảo vệ nệm có thể tháo giặt — đây là khoản đầu tư nhỏ giúp kéo dài đáng kể thời gian giữa các lần giặt chuyên sâu." },
      { p: "Mở cửa phòng ngủ cho thoáng vào ban ngày thay vì đóng kín. Độ ẩm tích trong phòng là điều kiện lý tưởng cho mạt bụi sinh sôi." },
    ],
  },
];
